apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp-frontend
  template:
    metadata:
      labels:
        app: testapp-frontend
    spec:
      containers:
        - name: testapp-frontend
          # GitHub Actions will replace this image URL
          image: REPLACE_ME
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testapp-frontend-service
spec:
  # This provides the Public IP (LoadBalancer)
  type: LoadBalancer
  selector:
    app: testapp-frontend
  ports:
    - port: 80
      targetPort: 80
